#!/usr/bin/env bash
#
# Generate a global AnalyzerConfig that limits the injected diagnostics to changed C# files.
#
#   tvrmsmith-scope-changed.sh <project-directory>
#
# Prints the absolute path of the generated config on stdout, and nothing at all if this is not
# a git repository or git could not answer. Local.props runs it before CoreCompile and adds the
# printed path to @(EditorConfigFiles), so a plain `dotnet build` — and every IDE design-time
# build — is scoped with no wrapper.
#
# Roslyn has no diff awareness: analyzers run over the whole compilation, always. On a mature
# codebase that is thousands of pre-existing sites, all of it in
# code nobody is being asked to change. The config below turns every injected id off globally
# and re-raises it to warning in a per-file section for each changed file.
#
# Two things about that config are load-bearing and fail silently when wrong:
#
#   * global_level = 100. The curated config deliberately sits at the default level 0. At equal
#     levels the conflicting entries cancel and the whole scoping config is ignored — measured,
#     and no conflict warning is emitted. Only global configs are ordered against each other, so
#     a matching entry in the target repo's own .editorconfig still outranks this regardless.
#   * Section paths must be absolute.
#
# Written for bash 3.2 (the macOS system bash).
set -uo pipefail

project_dir=${1:-}
[ -n "$project_dir" ] || exit 0

# Every injected id, not just the TVRM ones: FAA0001-FAA0004 arrive through the same injection
# and carry the same "code nobody is being asked to change" problem.
ids='TVRM0001 TVRM0002 TVRM0003 FAA0001 FAA0002 FAA0003 FAA0004'

# How long a generated config is reused before git is asked again. One build of the adoption
# target compiles ~60 projects and this runs once per project, so without a window the git cost
# is paid 60 times. Short enough that an edit is picked up on the next build either way.
ttl=${TVRMSMITH_SCOPE_TTL:-5}

command -v git >/dev/null 2>&1 || exit 0

repo_root=$(cd "$project_dir" 2>/dev/null && git rev-parse --show-toplevel 2>/dev/null) || exit 0
[ -n "$repo_root" ] || exit 0
# The injection is scoped by a StartsWith condition on the *resolved* project directory, so
# resolve here too or the paths written into the sections will not be the ones csc sees.
repo_root=$(cd "$repo_root" && pwd -P) || exit 0

out_dir=${TMPDIR:-/tmp}/tvrmsmith-scope
mkdir -p "$out_dir" 2>/dev/null || exit 0
out=$out_dir/$(printf '%s' "$repo_root" | tr -c 'A-Za-z0-9' '-').globalconfig

mtime_of() {
  if [ "$(uname)" = Darwin ]; then stat -f %m "$1" 2>/dev/null; else stat -c %Y "$1" 2>/dev/null; fi
}

if [ -f "$out" ]; then
  mtime=$(mtime_of "$out")
  if [ -n "$mtime" ] && [ $(( $(date +%s) - mtime )) -lt "$ttl" ]; then
    printf '%s\n' "$out"
    exit 0
  fi
fi

# Working tree against HEAD, plus untracked files. TVRMSMITH_SCOPE_SINCE=main widens that to
# everything the branch changed, which is the right setting when reviewing a branch rather than
# writing on it.
since=${TVRMSMITH_SCOPE_SINCE:-HEAD}
changed=$( cd "$repo_root" && {
  git diff --name-only --diff-filter=ACMR "$since" 2>/dev/null
  git ls-files --others --exclude-standard 2>/dev/null
} )

tmp=$(mktemp "$out_dir/.scope.XXXXXX") || exit 0
trap 'rm -f "$tmp"' EXIT

{
  echo '# Generated by tvrmsmith-scope-changed.sh — do not edit, it is rewritten every build.'
  echo "# Repository: $repo_root"
  echo "# Changed against: $since"
  echo
  echo 'is_global = true'
  echo 'global_level = 100'
  echo
  for id in $ids; do echo "dotnet_diagnostic.$id.severity = none"; done
} >"$tmp"

while IFS= read -r file; do
  [ -n "$file" ] || continue
  case "$file" in
    *.cs) ;;
    *) continue ;;
  esac
  case "$file" in
    */obj/*|obj/*|*/bin/*|bin/*) continue ;;
  esac
  [ -f "$repo_root/$file" ] || continue
  # An editorconfig section header is a glob, so the literal characters that mean something in
  # one have to be escaped or a path containing them silently matches nothing.
  section=$(printf '%s/%s' "$repo_root" "$file" | sed 's/[][*?{},\\]/\\&/g')
  {
    echo
    echo "[$section]"
    for id in $ids; do echo "dotnet_diagnostic.$id.severity = warning"; done
  } >>"$tmp"
done <<<"$changed"

# Replacing the file with identical content would still move its timestamp, and it is a csc
# input — every project in the tree would recompile on every build. Only publish a real change.
if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
  touch "$out" 2>/dev/null   # refresh the TTL window; the content is already right
else
  mv "$tmp" "$out" 2>/dev/null || exit 0
fi

printf '%s\n' "$out"
