#!/usr/bin/env bash
#
# Generate a global AnalyzerConfig that limits the injected diagnostics to changed C# files.
#
#   tvrmsmith-scope-changed.sh <project-directory>
#
# Prints the absolute path of the generated config on stdout, and nothing at all if this is not
# a git repository or git could not answer. Local.props runs it before CoreCompile and adds the
# printed path to @(EditorConfigFiles), so a plain `dotnet build` — and every IDE design-time
# build — is scoped with no wrapper.
#
# Roslyn has no diff awareness: analyzers run over the whole compilation, always. On a mature
# codebase that is thousands of pre-existing sites, all of it in
# code nobody is being asked to change. The config below turns every injected id off globally
# and re-raises it to warning in a per-file section for each changed file.
#
# Two things about that config are load-bearing and fail silently when wrong:
#
#   * global_level = 100. The curated config deliberately sits at the default level 0. At equal
#     levels the conflicting entries cancel and the whole scoping config is ignored — measured,
#     and no conflict warning is emitted. Only global configs are ordered against each other, so
#     a matching entry in the target repo's own .editorconfig still outranks this regardless.
#   * Section paths must be absolute.
#
# Written for bash 3.2 (the macOS system bash).
set -uo pipefail

project_dir=${1:-}
[ -n "$project_dir" ] || exit 0

# Every injected id, not just the TVRM ones: FAA0001-FAA0004 arrive through the same injection
# and carry the same "code nobody is being asked to change" problem.
ids='TVRM0001 TVRM0002 TVRM0003 FAA0001 FAA0002 FAA0003 FAA0004 CA1003 CA1005 CA1008 CA1012 CA1019 CA1021 CA1031 CA1032 CA1033 CA1034 CA1040 CA1043 CA1044 CA1045 CA1046 CA1052 CA1054 CA1055 CA1056 CA1058 CA1060 CA1063 CA1064 CA1065 CA1066 CA1307 CA1308 CA1501 CA1502 CA1505 CA1506 CA1508 CA1509 CA1700 CA1713 CA1721 CA1802 CA1810 CA1813 CA1815 CA1820 CA1823 CA1849 CA1851 CA1867 CA2002 CA2008 CA2025 CA2100 CA2119 CA2153 CA2207 CA2213 CA2214 CA2216 CA2217 CA2226 CA2234 CA2243 CA2300 CA2301 CA2302 CA2305 CA2310 CA2311 CA2312 CA2315 CA2321 CA2322 CA2326 CA2327 CA2328 CA2329 CA2330 CA2350 CA2351 CA2352 CA2353 CA2354 CA2355 CA2356 CA2361 CA2362 CA3001 CA3002 CA3003 CA3004 CA3005 CA3006 CA3007 CA3008 CA3009 CA3010 CA3011 CA3012 CA5358 CA5361 CA5362 CA5367 CA5375 CA5376 CA5377 CA5378 CA5380 CA5381 CA5382 CA5383 CA5386 CA5387 CA5388 CA5389 CA5390 CA5392 CA5393 CA5394 CA5395 CA5396 CA5398 CA5399 CA5400 CA5401 CA5402 CA5403 CA5404 CA5405'

# How long a generated config is reused before git is asked again. One build of the adoption
# target compiles ~60 projects and this runs once per project, so without a window the git cost
# is paid 60 times. Short enough that an edit is picked up on the next build either way.
ttl=${TVRMSMITH_SCOPE_TTL:-5}

command -v git >/dev/null 2>&1 || exit 0

repo_root=$(cd "$project_dir" 2>/dev/null && git rev-parse --show-toplevel 2>/dev/null) || exit 0
[ -n "$repo_root" ] || exit 0
# The injection is scoped by a StartsWith condition on the *resolved* project directory, so
# resolve here too or the paths written into the sections will not be the ones csc sees.
repo_root=$(cd "$repo_root" && pwd -P) || exit 0

out_dir=${TMPDIR:-/tmp}/tvrmsmith-scope
mkdir -p "$out_dir" 2>/dev/null || exit 0
out=$out_dir/$(printf '%s' "$repo_root" | tr -c 'A-Za-z0-9' '-').globalconfig

mtime_of() {
  if [ "$(uname)" = Darwin ]; then stat -f %m "$1" 2>/dev/null; else stat -c %Y "$1" 2>/dev/null; fi
}

if [ -f "$out" ]; then
  mtime=$(mtime_of "$out")
  if [ -n "$mtime" ] && [ $(( $(date +%s) - mtime )) -lt "$ttl" ]; then
    printf '%s\n' "$out"
    exit 0
  fi
fi

# Working tree against HEAD, plus untracked files. TVRMSMITH_SCOPE_SINCE=main widens that to
# everything the branch changed, which is the right setting when reviewing a branch rather than
# writing on it.
since=${TVRMSMITH_SCOPE_SINCE:-HEAD}
changed=$( cd "$repo_root" && {
  git diff --name-only --diff-filter=ACMR "$since" 2>/dev/null
  git ls-files --others --exclude-standard 2>/dev/null
} )

tmp=$(mktemp "$out_dir/.scope.XXXXXX") || exit 0
trap 'rm -f "$tmp"' EXIT

{
  echo '# Generated by tvrmsmith-scope-changed.sh — do not edit, it is rewritten every build.'
  echo "# Repository: $repo_root"
  echo "# Changed against: $since"
  echo
  echo 'is_global = true'
  echo 'global_level = 100'
  echo
  for id in $ids; do echo "dotnet_diagnostic.$id.severity = none"; done
} >"$tmp"

while IFS= read -r file; do
  [ -n "$file" ] || continue
  case "$file" in
    *.cs) ;;
    *) continue ;;
  esac
  case "$file" in
    */obj/*|obj/*|*/bin/*|bin/*) continue ;;
  esac
  [ -f "$repo_root/$file" ] || continue
  # An editorconfig section header is a glob, so the literal characters that mean something in
  # one have to be escaped or a path containing them silently matches nothing.
  section=$(printf '%s/%s' "$repo_root" "$file" | sed 's/[][*?{},\\]/\\&/g')
  {
    echo
    echo "[$section]"
    for id in $ids; do echo "dotnet_diagnostic.$id.severity = warning"; done
  } >>"$tmp"
done <<<"$changed"

# Replacing the file with identical content would still move its timestamp, and it is a csc
# input — every project in the tree would recompile on every build. Only publish a real change.
if [ -f "$out" ] && cmp -s "$tmp" "$out"; then
  touch "$out" 2>/dev/null   # refresh the TTL window; the content is already right
else
  mv "$tmp" "$out" 2>/dev/null || exit 0
fi

printf '%s\n' "$out"
